@startuml TaskFlow - Діаграма активності

title Процес генерації звіту

start

:Користувач запитує звіт;

if (Користувач авторизований?) then (так)
  :Перевірити права доступу;
  
  if (Має права на звіт?) then (так)
    :Отримати параметри звіту;
    
    fork
      :Зібрати дані про завдання;
    fork again
      :Зібрати дані про користувачів;
    end fork
    
    :Обробити дані;
    
    :Сформувати звіт;
    
    :Зберегти звіт у базі даних;
    
    :Надіслати звіт користувачу;
    
    :Показати повідомлення про успіх;
  else (ні)
    :Показати повідомлення про відсутність прав;
  endif
else (ні)
  :Перенаправити на сторінку авторизації;
  
  :Показати повідомлення про необхідність авторизації;
endif

stop

@enduml
